-- MySQL Script generated by MySQL Workbench
-- Mon Mar 31 12:05:07 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb3 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`movie` (
  `movie_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `overview` VARCHAR(250) NULL DEFAULT NULL,
  `popularity` DOUBLE NULL DEFAULT NULL,
  `release_date` DATE NULL DEFAULT NULL,
  `revenue` INT NULL DEFAULT NULL,
  `runtime` INT NULL DEFAULT NULL,
  `status` ENUM('RELEASED', 'RUMORED', 'POST_PRODUCTION') NULL DEFAULT NULL,
  `title` VARCHAR(45) NULL DEFAULT NULL,
  `vote_average` DOUBLE NULL DEFAULT NULL,
  `vote_count` INT NULL DEFAULT NULL,
  `budget` INT NULL DEFAULT NULL,
  `original_language` VARCHAR(2) NULL DEFAULT NULL,
  `original_title` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`movie_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`persona` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`crew`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`crew` (
  `PERSONA_id` INT NOT NULL,
  `Movie_movie_id` INT NOT NULL,
  `crew_role` VARCHAR(45) NULL DEFAULT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  INDEX `fk_PERSONA_has_Movie_Movie1_idx` (`Movie_movie_id` ASC) VISIBLE,
  INDEX `fk_PERSONA_has_Movie_PERSONA1_idx` (`PERSONA_id` ASC) VISIBLE,
  CONSTRAINT `fk_PERSONA_has_Movie_Movie1`
    FOREIGN KEY (`Movie_movie_id`)
    REFERENCES `mydb`.`movie` (`movie_id`),
  CONSTRAINT `fk_PERSONA_has_Movie_PERSONA1`
    FOREIGN KEY (`PERSONA_id`)
    REFERENCES `mydb`.`persona` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`cast`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cast` (
  `character` VARCHAR(45) NULL DEFAULT NULL,
  `gender` INT NULL DEFAULT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `Crew_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Crew_id`),
  INDEX `fk_Cast_Crew1_idx` (`Crew_id` ASC) VISIBLE,
  CONSTRAINT `fk_Cast_Crew1`
    FOREIGN KEY (`Crew_id`)
    REFERENCES `mydb`.`crew` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`genre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = big5;


-- -----------------------------------------------------
-- Table `mydb`.`genre_has_movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`genre_has_movie` (
  `Genre_id` INT NOT NULL,
  `Movie_id` INT NOT NULL,
  PRIMARY KEY (`Genre_id`, `Movie_id`),
  INDEX `fk_Genre_has_Movie_Movie1_idx` (`Movie_id` ASC) VISIBLE,
  INDEX `fk_Genre_has_Movie_Genre1_idx` (`Genre_id` ASC) VISIBLE,
  CONSTRAINT `fk_Genre_has_Movie_Genre1`
    FOREIGN KEY (`Genre_id`)
    REFERENCES `mydb`.`genre` (`id`),
  CONSTRAINT `fk_Genre_has_Movie_Movie1`
    FOREIGN KEY (`Movie_id`)
    REFERENCES `mydb`.`movie` (`movie_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = big5;


-- -----------------------------------------------------
-- Table `mydb`.`keywords`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`keywords` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`keywords_has_movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`keywords_has_movie` (
  `Keywords_id` INT NOT NULL,
  `Movie_movie_id` INT NOT NULL,
  PRIMARY KEY (`Keywords_id`, `Movie_movie_id`),
  INDEX `fk_Keywords_has_Movie_Movie1_idx` (`Movie_movie_id` ASC) VISIBLE,
  INDEX `fk_Keywords_has_Movie_Keywords1_idx` (`Keywords_id` ASC) VISIBLE,
  CONSTRAINT `fk_Keywords_has_Movie_Keywords1`
    FOREIGN KEY (`Keywords_id`)
    REFERENCES `mydb`.`keywords` (`id`),
  CONSTRAINT `fk_Keywords_has_Movie_Movie1`
    FOREIGN KEY (`Movie_movie_id`)
    REFERENCES `mydb`.`movie` (`movie_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`spoken_language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`spoken_language` (
  `ISO_639_1` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ISO_639_1`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`movie_has_spoken_language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`movie_has_spoken_language` (
  `Movie_id` INT NOT NULL,
  `Spoken_language_ISO_639_1` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Movie_id`, `Spoken_language_ISO_639_1`),
  INDEX `fk_Movie_has_Spoken_language_Spoken_language1_idx` (`Spoken_language_ISO_639_1` ASC) VISIBLE,
  INDEX `fk_Movie_has_Spoken_language_Movie1_idx` (`Movie_id` ASC) VISIBLE,
  CONSTRAINT `fk_Movie_has_Spoken_language_Movie1`
    FOREIGN KEY (`Movie_id`)
    REFERENCES `mydb`.`movie` (`movie_id`),
  CONSTRAINT `fk_Movie_has_Spoken_language_Spoken_language1`
    FOREIGN KEY (`Spoken_language_ISO_639_1`)
    REFERENCES `mydb`.`spoken_language` (`ISO_639_1`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`production_companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`production_companies` (
  `name` VARCHAR(45) NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`production_companies_has_movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`production_companies_has_movie` (
  `Production_companies_id` INT NOT NULL,
  `Movie_movie_id` INT NOT NULL,
  PRIMARY KEY (`Production_companies_id`, `Movie_movie_id`),
  INDEX `fk_Production_companies_has_Movie_Movie1_idx` (`Movie_movie_id` ASC) VISIBLE,
  INDEX `fk_Production_companies_has_Movie_Production_companies1_idx` (`Production_companies_id` ASC) VISIBLE,
  CONSTRAINT `fk_Production_companies_has_Movie_Movie1`
    FOREIGN KEY (`Movie_movie_id`)
    REFERENCES `mydb`.`movie` (`movie_id`),
  CONSTRAINT `fk_Production_companies_has_Movie_Production_companies1`
    FOREIGN KEY (`Production_companies_id`)
    REFERENCES `mydb`.`production_companies` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`production_countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`production_countries` (
  `ISO_3166_1` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ISO_3166_1`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`production_countries_has_movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`production_countries_has_movie` (
  `production_countries_ISO_3166_1` VARCHAR(45) NOT NULL,
  `Movie_id` INT NOT NULL,
  PRIMARY KEY (`production_countries_ISO_3166_1`, `Movie_id`),
  INDEX `fk_production_countries_has_Movie_Movie1_idx` (`Movie_id` ASC) VISIBLE,
  INDEX `fk_production_countries_has_Movie_production_countries1_idx` (`production_countries_ISO_3166_1` ASC) VISIBLE,
  CONSTRAINT `fk_production_countries_has_Movie_Movie1`
    FOREIGN KEY (`Movie_id`)
    REFERENCES `mydb`.`movie` (`movie_id`),
  CONSTRAINT `fk_production_countries_has_Movie_production_countries1`
    FOREIGN KEY (`production_countries_ISO_3166_1`)
    REFERENCES `mydb`.`production_countries` (`ISO_3166_1`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `rol` ENUM('usuario', 'administrador', 'editor', 'recomendador', 'analista') NULL DEFAULT 'usuario',
  `user_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`review` (
  `Movie_movie_id` INT NOT NULL,
  `Usuario_email` VARCHAR(255) NOT NULL,
  `comment` VARCHAR(150) NULL DEFAULT NULL,
  `rate` DOUBLE NULL DEFAULT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`Movie_movie_id`, `Usuario_email`),
  INDEX `fk_Movie_has_Usuario_Usuario2_idx` (`Usuario_email` ASC) VISIBLE,
  INDEX `fk_Movie_has_Usuario_Movie2_idx` (`Movie_movie_id` ASC) VISIBLE,
  CONSTRAINT `fk_Movie_has_Usuario_Movie2`
    FOREIGN KEY (`Movie_movie_id`)
    REFERENCES `mydb`.`movie` (`movie_id`),
  CONSTRAINT `fk_Movie_has_Usuario_Usuario2`
    FOREIGN KEY (`Usuario_email`)
    REFERENCES `mydb`.`usuario` (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`usersavemovie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usersavemovie` (
  `Movie_movie_id` INT NOT NULL,
  `Usuario_email` VARCHAR(255) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Movie_movie_id`, `Usuario_email`),
  INDEX `fk_Movie_has_Usuario_Usuario1_idx` (`Usuario_email` ASC) VISIBLE,
  INDEX `fk_Movie_has_Usuario_Movie1_idx` (`Movie_movie_id` ASC) VISIBLE,
  CONSTRAINT `fk_Movie_has_Usuario_Movie1`
    FOREIGN KEY (`Movie_movie_id`)
    REFERENCES `mydb`.`movie` (`movie_id`),
  CONSTRAINT `fk_Movie_has_Usuario_Usuario1`
    FOREIGN KEY (`Usuario_email`)
    REFERENCES `mydb`.`usuario` (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
